### ISSUE TITLE
[feat] security을 사용한 사용자 로그인 기능 구현 

### ISSUE THREAD

**Issue by imojaek** [BoWS-Bo-Web-Service/BoWS-Back#10]
Spring Security를 사용해서 구현

- Role
  - Admin : 관리자 계정 (모든 조작 가능)
  - User : 일반 사용자 계정 (자신의 프로젝트 CRUD 가능토록)
  - Read-Only : 게스트 계정 (단순 조회만 가능)
  
단순 ID/PW 로그인으로, Role 구현에 초점.

**Comment by seedspirit** [comment]
**요구사항 추가**
- user의 경우 특정 코드를 입력해야만 회원가입 가능 (회원가입 인원 제한을 위함)
- 게스트 계정의 경우 회원가입 로직 자체는 필요하지 않고 해당 role 자체만 구현하는 방식 (미리 만들어진 id, pw를 돌려쓰는 방식)
